// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTolQOvWA7OxalU79rSq12MYJ9zR_pcXQ',
    appId: '1:433590556232:web:9c7c050a9ae39d9a98ea7d',
    messagingSenderId: '433590556232',
    projectId: 'drivetest-sniper',
    authDomain: 'drivetest-sniper.firebaseapp.com',
    storageBucket: 'drivetest-sniper.firebasestorage.app',
    measurementId: 'G-Q6L2EVBNNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnZc5giqaDdpqjY8EMlX55L0z6DlsxJRI',
    appId: '1:433590556232:android:76bf91b79108654898ea7d',
    messagingSenderId: '433590556232',
    projectId: 'drivetest-sniper',
    storageBucket: 'drivetest-sniper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBngTda9pBDOR62kX47wjbY7wKV-Mcm5mI',
    appId: '1:433590556232:ios:4be15bcb2e54120c98ea7d',
    messagingSenderId: '433590556232',
    projectId: 'drivetest-sniper',
    storageBucket: 'drivetest-sniper.firebasestorage.app',
    iosBundleId: 'com.example.driveTestSniper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBngTda9pBDOR62kX47wjbY7wKV-Mcm5mI',
    appId: '1:433590556232:ios:4be15bcb2e54120c98ea7d',
    messagingSenderId: '433590556232',
    projectId: 'drivetest-sniper',
    storageBucket: 'drivetest-sniper.firebasestorage.app',
    iosBundleId: 'com.example.driveTestSniper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTolQOvWA7OxalU79rSq12MYJ9zR_pcXQ',
    appId: '1:433590556232:web:8be9cbe7c998d66e98ea7d',
    messagingSenderId: '433590556232',
    projectId: 'drivetest-sniper',
    authDomain: 'drivetest-sniper.firebaseapp.com',
    storageBucket: 'drivetest-sniper.firebasestorage.app',
    measurementId: 'G-Y8XHPHWF8D',
  );
}
